# YAML pipeline
# Build, test, and publish NuGet package to Azure Artifacts Feed

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  artifactName: 'StringLibrary.1.0.0.nupkg'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '>=5.8.0'
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration)'
    platform: 'Any CPU'
    clean: true

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\$(buildConfiguration)\*test*.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.Repository.LocalPath)\StringLibrary\StringLibrary.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'BUILD_BUILDNUMBER'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    arguments: '--include-symbols'

- task: NuGetAuthenticate@0
  inputs:
    artifactFeeds: 'nugetfeed'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)\$(artifactName).$(Build.BuildNumber).nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'nugetfeed'
