trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  feedName: 'nugetfeed'
  packageName: 'StringLibrary'
  packageVersion: '$(Build.BuildNumber)'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'nugetfeed'
    includeNuGetOrg: false

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'
    includeSymbols: true
    includeSource: true
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: '"https://pkgs.dev.azure.com/aadepo10/NugetPackage/_packaging/nugetfeed/nuget/v3/index.json"'
    ignoreInvalidServiceConnection: true

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'nugetfeed'
    allowPackageConflicts: true
    versioningScheme: 'byBuildNumber'
    authType: 'serviceEndpoint'
    serviceEndpoint: 'https://pkgs.dev.azure.com/aadepo10/NugetPackage/_packaging/nugetfeed/nuget/v3/index.json'
